# Generated by Django 4.0.4 on 2023-06-01 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_calories_goal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calories_goal',
            old_name='Colories',
            new_name='Calories',
        ),
    ]
