# Generated by Django 4.0.4 on 2023-06-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_calories_goal_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calories_goal',
            name='Calories',
            field=models.CharField(max_length=10),
        ),
    ]
