# Generated by Django 4.0.4 on 2023-06-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_calories_goal_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calories_goal',
            name='Calories',
            field=models.IntegerField(),
        ),
    ]
